### PR TITLE
Maybe mongoid 6

### PR DESCRIPTION
**Pull request by DarthHater**
Hi there,

I needed to get MongoID 6 working with this (to upgrade to rails 5). Here's what I've done thus far. If you want me to change anything let me know!

### CODE REVIEW

**Comment by tboerger** [comment]
I'm not using this project anymore, so maybe you want to take it? https://github.com/tbpro/mongoid_userstamp/issues/33

**Comment by DarthHater** [comment]
@tboerger let me discuss with some others. We use it, but none of us have scads of time. I'll see what the temperature is.

**Comment by DarthHater** [comment]
@javierav any chance this can get traction? @lomky @colinxfleming and I use a fork of this project on a repo and it would be nice to get rid of our fork!

**Comment by javierav** [comment]
I promise to work on this in the incoming days! 👌

**Comment by lomky** [comment]
We are no longer on MongoDB or using our fork, so this PR can be closed!

**Pull request closed without merging**
